version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    command: ["--config.file=/prometheus-config/prometheus.yml"]
    volumes:
      - ./prometheus-config:/prometheus-config
      - ./data/prometheus:/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

networks:
  default:
    external:
      name: app-network