global:
  scrape_interval: 5s

scrape_configs:

- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090

- job_name: app
  static_configs:
    - targets:
        - nginx:80

- job_name: 'node'
  static_configs:
    - targets: ['app:9100']